###
GET https://api.huddle.test/membership/entry HTTP/1.1 
Accept: application/vnd.huddle.data+json
Authorization: Bearer <replace_with_auth_token>

### Use triple hash to separate requests

PUT https://api.huddle.test/membership/users/921114/editable HTTP/1.1
Accept: application/vnd.huddle.data+json
Content-Type: application/vnd.huddle.data+json
Authorization: Bearer <replace_with_auth_token>

{
    "firstName": "Jonny",
    "lastName": "Olliff-Lee",
    "email": "jonny.admin@huddle.test",
    "company": "Huddle - Development",
    "role": "Document Writer",
    "aboutMe": "Some interesting information about me",
    "secondaryEmail": "jonny@personaldomain.com",
    "address": "The interwebz",
    "phone": "01234 567890",
    "mobile": "07712 345678"
}